bookmanage/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.index,name='index'),

    path('base/',views.base,name="base"),

    path('book/add/',views.book_add,name="book_add"),
    path('books/add/',views.books_add,name="books_add"),

    path('query/',views.query,name='query'),
    path('query/books/',views.query_books,name='query_books'),
    path('card/',views.card,name='card'),
    path('card/login/',views.card_login,name='card_login'),
    path('card/login/notexists/',views.card_login_notexists,name='card_login_notexists'),
    path('card/handle/',views.card_handle,name='card_handle'),
    path('card/login/handle/',views.card_login_handle,name='card_login_handle'),
    path('card/exit/',views.card_exit,name='card_exit'),
    path('card/exists/',views.card_exists,name='card_exists'),
    path('card/books/',views.card_books,name='card_books'),
    path('cards/query/',views.cards_query,name='cards_query'),
    path('card/delete/',views.card_delete,name='card_delete'),
    path('card/borrowed/',views.card_borrowed,name='card_borrowed'),

    path('booktitle/query/',views.booktitle_query,name='booktitle_query'),
    path('books/query/',views.books_query,name="books_query"),
    path('bookid_cardid/exists/',views.bookid_cardid_exists,name='bookid_cardid_exists'),


    path('manager/',views.manager,name='manager'),
    path('manager/login/',views.manager_login,name='manager_login'),
    path('manager/login/notexists',views.manager_login_notexists,name='manager_login_notexists'),
    path('manager/login/handle/',views.manager_login_handle,name='manager_login_handle'),
    path('manager/exit/',views.manager_exit,name='manager_exit'),
    path('manager/create/',views.manager_create,name='manager_create'),
    path('manager/create/handle/',views.manager_create_handle,name='manager_create_handle'),
    path('manager/add/books/',views.manager_add_books,name='manager_add_books'),
    path('manager/add/card/',views.manager_add_card,name='manager_add_card'),
    path('manager/add/card/handle/',views.manager_add_card_handle,name='manager_add_card_handle'),
    path('manager/exists/', views.manager_exists, name='manager_exists'),

]

books/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('bookmanage.urls','bookmanage'),namespace='bookmanage')),
]

bookmanage/models.py
from django.db import models
from hashlib import sha1
# Create your models here.
class Book(models.Model):
    category=models.CharField(max_length=10)
    title=models.CharField(max_length=40)
    press=models.CharField(max_length=30)
    year=models.IntegerField()
    author=models.CharField(max_length=20)
    price=models.DecimalField(max_digits=7,decimal_places=2)
    total=models.IntegerField()
    stock=models.IntegerField()
    def __str__(self):
        return str(self.pk)
    def serialize(self):
        return self.__dict__
    class Meta():
        db_table='book'
    @classmethod
    def create(cls,category,title,press,year,author,price,total,stock):
        b=Book()
        b.category=category
        b.title=title
        b.press=press
        b.year=year
        b.author=author
        b.price=price
        b.total=total
        b.stock=stock
        return b

class Card(models.Model):
    name=models.CharField(max_length=20)
    department=models.CharField(max_length=40)
    type=models.BooleanField()
    def __str__(self):
        return str(self.pk)
    class Meta():
        db_table='card'
    @classmethod
    def create(cls,name,department,type):
        c=Card()
        c.name=name
        c.department=department
        c.type=type
        return c

class Manager(models.Model):
    password=models.CharField(max_length=40)
    name=models.CharField(max_length=20)
    contact=models.CharField(max_length=20)
    def __str__(self):
        return str(self.pk)
    class Meta():
        db_table='manager'
    @classmethod
    def create(cls,pwd,name,contact):
        m=Manager()
        pwd_en = sha1(pwd.encode('utf-8')).hexdigest()
        m.password=pwd_en
        m.name=name
        m.contact=contact
        return m

class BorrowRecord(models.Model):
    borrow_date=models.DateField()
    return_date=models.DateField()
    book=models.ForeignKey('Book',on_delete=models.CASCADE)
    card=models.ForeignKey('Card',on_delete=models.CASCADE)
    return_manager=models.ForeignKey('Manager',on_delete=models.CASCADE)
    def __str__(self):
        return str(self.pk)
    class Meta():
        db_table='borrowrecord'
    @classmethod
    def create(cls,borrow_date,return_date,book_id,card_id,return_manager_id):
        br=BorrowRecord()
        br.borrow_date=borrow_date
        br.return_date=return_date
        br.book_id=book_id
        br.card_id=card_id
        br.return_manager_id=return_manager_id
        return br

bookmanage/views.py
from django.shortcuts import render,redirect,reverse
from .models import *
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from hashlib import sha1
import json

# Create your views here.
def index(request):
    err_name=request.GET.get('err_name',0)
    err_pwd=request.GET.get('err_pwd',0)
    username=request.GET.get('username',"")
    context={'title':'首页','err_name':json.dumps(err_name),'err_pwd':json.dumps(err_pwd),'username':json.dumps(username)}
    return render(request,'bookmanage/index.html',context)

def query(request):
    context={"title":"查询"}
    return render(request,'bookmanage/query.html',context)

def query_books(request):
    post=request.POST

    books=Book.objects.all()
    count=0
    value=post.get('title',default="")
    if len(value)!=0:
        count+=1
        books=books.filter(title=value)

    value = post.get('author', default="")
    if len(value) != 0:
        count+=1
        books = books.filter(author=value)

    value = post.get('press', default="")
    if len(value) != 0:
        count += 1
        books = books.filter(press=value)

    value = post.get('year', default="")
    if len(value) != 0:
        count += 1
        books = books.filter(year=int(value))

    value = post.get('category', default="")
    # print(post)
    # print(value)
    if len(value) != 0:
        count += 1
        books = books.filter(category=value)

    value=post.get('price',default="")
    if len(value)!=0:
        count += 1
        books=books.filter(price=float(value))

    value = post.get('total', default="")
    if len(value) != 0:
        count += 1
        books = books.filter(total=int(value))

    value = post.get('stock', default="")
    if len(value) != 0:
        count += 1
        books = books.filter(stock=int(value))

    books=list(books.values())
    # print(books)
    if count==0:
        books=[]
    # print(count)
    return JsonResponse({"data":books})


def card(request):
    card_name=request.session.get('card_name',default=None)
    if card_name is None:
        return redirect(reverse("bookmanage:card_login"))
    res=Card.objects.filter(name=card_name)
    if len(res) == 0:
        return redirect(reverse("bookmanage:card_login"))
    brs=BorrowRecord.objects.filter(card_id=res[0].id)
    bookidlist=[]
    for br in brs:
        bookidlist.append(br.book_id)
    booklist=list(Book.objects.filter(pk__in=bookidlist))
    context={'booklist':booklist,"card_name":json.dumps(card_name),"card_name_org":card_name,"title":"借书/还书"}
    return render(request,'bookmanage/card.html',context)

def card_login(request):
    return render(request,'bookmanage/card_login.html')

def card_login_handle(request):
    card_name=request.POST.get('card_name')
    res=Card.objects.get(name=card_name)
    request.session['card_name']=card_name
    return redirect(reverse("bookmanage:card"))

def card_login_notexists(request):
    return render(request,'bookmanage/card_login_notexists.html')

def card_handle(request):
    option=request.POST['option_card']
    # print(request.POST['book_id'])# empty
    book_id=int(request.POST['book_id'])

    card_name=request.session['card_name']
    card_res=Card.objects.filter(name=card_name)
    card_id=card_res[0].id
    brs=BorrowRecord.objects.filter(card_id=card_id)
    bookids=[]
    for br in brs:
        bookids.append(br.book_id)
    from datetime import date

    test=Book.objects.filter(pk=book_id)
    if len(test) == 0:
        return render(request,'bookmanage/book_notexists.html')

    if option == "borrow":
        if book_id not in bookids:
            bof=Book.objects.get(pk=book_id)
            if bof.stock == 0:
                return render(request,'bookmanage/card_handle.html')
            else:
                bof.stock-=1
                bof.save()
                br=BorrowRecord.create(date.today(),date.today().replace(month=date.today().month+1),
                                   book_id,card_id,1)
                br.save()
    elif option == "return":
        if book_id in bookids  :
            bof = Book.objects.get(pk=book_id)
            bof.stock+=1
            bof.save()
            BorrowRecord.objects.filter(book_id=book_id,card_id=card_id).delete()
        else:
            return render(request, 'bookmanage/card_handle.html')
    return redirect(reverse('bookmanage:card'))
def card_exit(request):
    if request.session.get('card_name',default=None) is None:
        return redirect(reverse("bookmanage:card"))
    else:
        del request.session['card_name']
        return redirect(reverse("bookmanage:card"))
def card_exists(request):
    get=request.GET
    name=get.get('card_name',default="")
    res=Card.objects.filter(name=name).count()
    return JsonResponse({"count":res})

def card_books(request):
    card_name=request.GET['card_name']
    card=Card.objects.filter(name=card_name)
    card_id=card[0].id
    brs=BorrowRecord.objects.filter(card_id=card_id)
    bookids=[br.book_id for br in brs]
    books=list(Book.objects.filter(pk__in=bookids).values())
    # print(books)
    return JsonResponse({"data":books})

def cards_query(request):
    cards=Card.objects.all().values()
    cards=list(cards)
    return JsonResponse({"data":cards})

def card_delete(request):
    card_id=request.GET['card_id']
    card=Card.objects.filter(id=card_id)
    if len(card)==0:
        return JsonResponse({"data":[0]})
    card.delete()
    del request.session['card_name']
    return JsonResponse({"data":[1]})

def card_borrowed(request):
    card_id=request.GET.get('card_id')
    count=BorrowRecord.objects.filter(card_id=card_id).count()
    return JsonResponse({"data":count})


def booktitle_query(request):
    title=request.GET.get('title',default="")
    books=Book.objects.filter(title=title).values()
    books=list(books)
    # print(books)
    return JsonResponse({"data":books})

def books_query(request):
    books=Book.objects.all().values()
    books=list(books)
    return JsonResponse({"data":books})


def bookid_cardid_exists(request):
    bookid=request.GET['book_id']
    card_name = request.session['card_name']
    card=Card.objects.filter(name=card_name)
    card_id=card[0].id
    count=BorrowRecord.objects.filter(card_id=card_id).filter(book_id=bookid).count()
    return JsonResponse({"data":count})


# manager
def manager(request):
    manager_name=request.session.get('manager_name',default=None)
    state=request.session.get('manager_state',default=0)
    if manager_name is None:
        return redirect(reverse("bookmanage:index"))

    context={"manager_name":manager_name,"title":"管理员"}
    return render(request,"bookmanage/manager.html",context)
def manager_login(request):
    return render(request,'bookmanage/manager_login.html')
def manager_login_notexists(request):
    return render(request,'bookmanage/manager_login_notexists.html')
def manager_login_handle(request):
    manager_name=request.POST.get('manager_name')
    query_res=Manager.objects.filter(name=manager_name)
    pwd=request.POST.get('manager_pwd',default="")
    pwd_en=sha1(pwd.encode('utf-8')).hexdigest()
    if pwd_en == query_res[0].password:
        request.session['manager_name']=manager_name
        request.session.set_expiry(0)
        return redirect(reverse("bookmanage:manager"))
    else:
        hrr=HttpResponseRedirect(reverse("bookmanage:index")+'?err_pwd=1&username='+manager_name)
        return hrr
def manager_exit(request):
    if request.session.get('manager_name',default=None) is None:
        return redirect(reverse("bookmanage:manager"))
    else:
        del request.session['manager_name']
        return redirect(reverse("bookmanage:manager"))
def manager_create(request):
    context={"title":"注册"}
    return render(request,"bookmanage/manager_create.html",context)
def manager_create_handle(request):
    m=Manager.create(request.POST['pwd'],request.POST['name'],request.POST['contact'])
    m.save()
    return redirect(reverse("bookmanage:index"))

def manager_add_books(request):
    import csv
    f=request.FILES['csv']
    import os
    from books.settings import BASE_DIR
    filename=os.path.join(BASE_DIR,'static/bookmanage/',f.name)
    with open(filename,"wb") as file:
        for c in f.chunks():
            file.write(c)
    with open(filename,"r",encoding='utf-8') as file:
        reader=csv.reader(file)
        reader=list(reader)
        for book in reader:
            b=Book.create(book[0],book[1],book[2],int(book[3]),book[4],float(book[5]),int(book[6]),int(book[7]))
            b.save()
    request.session['manager_state']=1
    return redirect(reverse("bookmanage:manager"))
def manager_add_card(request):
    if request.POST['card_type']=="teacher":
        type=1
    else:
        type=0
    c=Card.create(request.POST['card_name'],request.POST['card_dept'],type)
    c.save()
    # print('hello')
    return redirect(reverse("bookmanage:manager"))

def manager_add_card_handle(request):
    return render(request,'bookmanage/manager_add_card_handle.html')

def manager_exists(request):
    name=request.GET.get('name',"")
    count=Manager.objects.filter(name=name).count()
    return JsonResponse({"count":count})

def base(request):
    return render(request,'base.html')


def book_add(request):
    post=request.POST
    # print(post.get('cat'))
    book=Book.create(post.get('cat'),post.get('title'),post.get('press'),int(post.get('year')),post.get('author'),
              float(post.get('price')),int(post.get('total')),int(post.get('stock')))
    book.save()
    return redirect(reverse("bookmanage:manager"))

def books_add(request):
    request.session['manager_state']=0
    return render(request,'bookmanage/books_add.html')

templates/bookmanage/book_notexists.html
{% extends "bookmanage/fail.html" %}
{% block content %}
    No this book!

{% endblock content %}

templates/bookmanage/books_add.html
{% extends 'bookmanage/manager.html' %}

templates/bookmanage/card.html
{% extends 'base.html' %}
{% block css %}
    <style>
        #card #user, #card #book {
            padding: 50px;
        }

        #card #user h3 {
            margin-bottom: 20px;
        }

        #card button {
            margin-left: 20px;
        }

        #card .btn-outline-secondary {
            margin: 0;
            padding: 1px 10px;
        }

        #card .borrow {
        }

        #card .return {
        }

        #card .above {
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
{% endblock css %}
{% block body %}

    {#    card#}
    <section id="card">
        <div class="container">
            <div class="row">
                <div class="col-md-6" id="user">
                    <div class="row">
                        <div class="col-md-8"><h3>您好,{{ card_name_org }}</h3></div>
                        <div class="col-md-4">
                            <a href="{% url "bookmanage:card_exit" %}" role="button"
                               class="btn btn-secondary above">退出</a>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">已借书籍</div>
                        <div class="card-body">
                            <table class="table" id="borrowed">
                                <thead>
                                <tr>
                                    <th>id</th>
                                    <th>书名</th>
                                    <th>作者</th>
                                    <th>总量</th>
                                    <th>库存</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody id="brw_body">

                                </tbody>
                            </table>
                            <div id="page_con"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" id="book">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group form-inline">
                                <input type="text" class="form-control" id="qt" name="qt" placeholder="请输入书名">
                                <button class="btn btn-secondary above" type="button" id="queryBtn">查询</button>
                                <button class="btn btn-secondary above" type="button" id="allBtn">查看全部</button>
                            </div>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>id</th>
                                    <th>书名</th>
                                    <th>作者</th>
                                    <th>总量</th>
                                    <th>库存</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody id="bt_query">

                                </tbody>
                            </table>
                            <div id="page_con2"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {#    card#}

    {{ message|default:"" }}
{% endblock body %}
{% block js %}
    <script>
        $(function () {
            set_all();

            var $brw = $('#brw_body');

            var url = "/card/books/?card_name=" +{{ card_name|safe }};
            var l = []
            $.get(url, function (data) {
                $('#page_con').empty();
                $brw.empty();
                l.splice(0, l.length);
                if (data.data.length == 0)
                    return;
                $.each(data.data, function (index, book) {
                    l[index] = "<tr><td>" + book['id'] + "</td><td>" + book['title'] + "</td><td>" + book['author'] + "</td><td>" + book['total'] + "</td><td>" + book['stock'] + "</td><td><button class='btn btn-outline-secondary return' type='button' id='brwBtn'>还书</button></td></tr>";
                })
                $('#page_con').pagination({
                    dataSource: l,
                    pageSize: 10,
                    showGoInput: true,
                    showGoButton: true,
                    callback: function (data, pagination) {
                        var html = "";
                        var pageSize = pagination.pageSize;
                        for (var i = pageSize * (pagination.pageNumber - 1); i < pageSize * pagination.pageNumber; i++) {
                            html += l[i];
                        }
                        $brw.html(html);
                        $('.return').bind('click', function () {
                            var j = {
                                "option_card": "return",
                                "book_id": $(this).parent().siblings().eq(0).text(),
                                "csrfmiddlewaretoken": '{{csrf_token}}'
                            };
                            $.post('/card/handle/', j, function () {
                                location.reload();
                            })
                        })
                    }
                })
            })

            //query by title
            var $bt_query = $("#bt_query");
            var bl = []
            var $query_btn = $('#queryBtn');
            $query_btn.bind('click', function () {
                var url = "/booktitle/query/?title=" + $('#qt').val();

                $.get(url, function (data) {


                    $bt_query.empty();
                    $('#page_con2').empty();
                    bl.splice(0, bl.length);
                    if (data.data.length == 0)
                        return;
                    $.each(data.data, function (index, book) {
                        bl[index] = "<tr><td>" + book['id'] + "</td><td>" + book['title'] + "</td><td>" + book['author'] + "</td><td>" + book['total'] + "</td><td>" + book['stock'] + "</td><td><button class='btn btn-outline-secondary borrow' type='button' id='brwBtn'>借书</button></td></tr>";
                    })
                    $('#page_con2').pagination({
                        dataSource: bl,
                        pageSize: 10,
                        showGoInput: true,
                        showGoButton: true,
                        callback: function (data, pagination) {
                            var html = "";
                            var pageSize = pagination.pageSize;
                            for (var i = pageSize * (pagination.pageNumber - 1); i < pageSize * pagination.pageNumber; i++) {
                                html += bl[i];
                            }
                            $bt_query.html(html);
                            $('.borrow').bind('click', function () {
                                var url = '/bookid_cardid/exists/?book_id=' + $(this).parent().siblings().eq(0).text();
                                var $this = $(this);
                                $.get(url, function (data) {
                                    if (data.data == '1') {
                                        alert('借阅失败,您已经借过该书啦!');
                                        return;
                                    }
                                    if ($this.parent().prev().text() == '0') {
                                        alert('借阅失败,已经没有库存啦!')
                                        return;
                                    }
                                    var j = {
                                        "option_card": "borrow",
                                        "book_id": $this.parent().siblings().eq(0).text(),
                                        "csrfmiddlewaretoken": '{{csrf_token}}'
                                    };
                                    $.post('/card/handle/', j, function () {
                                        location.reload();
                                    })
                                })

                            })
                        }
                    })
                })
            })

            //all
            $('#allBtn').bind('click', set_all);

            function set_all() {
                var url = "/books/query/";

                $.get(url, function (data) {
                    $('#page_con2').empty();
                    $bt_query.empty();
                    bl.splice(0, bl.length);
                    if (data.data.length == 0)
                        return;
                    $.each(data.data, function (index, book) {
                        bl[index] = "<tr><td>" + book['id'] + "</td><td>" + book['title'] + "</td><td>" + book['author'] + "</td><td>" + book['total'] + "</td><td>" + book['stock'] + "</td><td><button class='btn btn-outline-secondary borrow' type='button' id='brwBtn'>借书</button></td></tr>";
                    })
                    $('#page_con2').pagination({
                        dataSource: bl,
                        pageSize: 10,
                        showGoInput: true,
                        showGoButton: true,
                        callback: function (data, pagination) {
                            var html = "";
                            var pageSize = pagination.pageSize;
                            for (var i = pageSize * (pagination.pageNumber - 1); i < pageSize * pagination.pageNumber; i++) {
                                html += bl[i];
                            }
                            $bt_query.html(html);
                            $('.borrow').bind('click', function () {
                                var url = '/bookid_cardid/exists/?book_id=' + $(this).parent().siblings().eq(0).text();
                                var $this = $(this);
                                $.get(url, function (data) {
                                    if (data.data == '1') {
                                        alert('借阅失败,您已经借过该书啦!');
                                        return;
                                    }
                                    if ($this.parent().prev().text() == '0') {
                                        alert('借阅失败,已经没有库存啦!')
                                        return;
                                    }
                                    var j = {
                                        "option_card": "borrow",
                                        "book_id": $this.parent().siblings().eq(0).text(),
                                        "csrfmiddlewaretoken": '{{csrf_token}}'
                                    };
                                    $.post('/card/handle/', j, function () {
                                        location.reload();
                                    })
                                })

                            });
                        }
                    })
                })
            }

            function check_already_borrowed(book_id) {
                console.log($('#brw_body').children().children().eq(0).text());
            }

            $(document).keyup(function (event) {
                if (event.keyCode == 13&&$('#qt').is(':focus')) {
                    $("#queryBtn").trigger("click");
                }
            });

        });
    </script>
{% endblock js %}

templates/bookmanage/card_handle.html
{% extends "bookmanage/fail.html" %}
{% block content %}
    Fail!

{% endblock content %}

templates/bookmanage/index.html
{% extends 'base.html' %}
{% block css %}

    <link rel="stylesheet" href="/static/css/index.css">
{% endblock css %}
{% block body %}

    {#    homepage#}
    <section id="homepage">
        <div class="container">
            <div class="row">
                <div class="col-md-7" id="imgCol">
                    <img src="/static/img/book2.png" class="img-fluid" alt="books">
                </div>
                <div class="col-md-5" id="loginCol">
                    <div class="card">
                        <div class="card-header">管理员登录</div>
                        <form action="{% url "bookmanage:manager_login_handle" %}" method="post" id="loginForm">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="manager_name">用户名</label>
                                <input type="text" class="form-control" id="manager_name" name="manager_name"
                                       aria-describedby="textHelp" placeholder="请输入用户名">
                                <small id="manage_id_help" class="form-text text-danger">请输入包含数字,字母或下划线的5到11位用户名</small>
                            </div>
                            <div class="form-group">
                                <label for="manager_pwd">密码</label>
                                <input type="password" class="form-control" id="manager_pwd" name="manager_pwd"
                                       placeholder="请输入密码">
                                <small id="manage_pwd_help" class="form-text text-danger">请输入包含数字,字母或下划线的8到20位密码</small>

                            </div>
                            <button type="submit" class="btn btn-outline-secondary float-right" id="login">登录</button>

                            <a role="button" href="{% url "bookmanage:manager_create" %}"
                               class="btn btn-outline-secondary float-right">注册</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {#    homepage#}


{% endblock %}
{% block js %}
    {#    <script type="text/javascript" src="/static/js/index.js"></script>#}
    <script>

        $(function () {

            var $name = $('#manager_name');
            var $pwd = $('#manager_pwd');
            var err_name1 = true, err_pwd1 = true;
            $name.bind("blur", function () {
                check_name();
            })

            $pwd.bind('blur', function () {
                check_pwd();
            })
            $name.bind('focus', function () {
                $name.next().hide();
            })
            $pwd.bind('focus', function () {
                $pwd.next().hide();
            })

            if ({{ err_pwd|safe }}==1
        )
            {
                $pwd.next().html('密码错误').show();
            }
            if ({{ err_name|safe }}==1
        )
            {

                $name.next().html('用户名错误').show();
            }


            $name.val({{ username|safe }});

            var re_name = /^\w{5,15}$/i;

            function check_name() {
                if (re_name.test($name.val())) {
                    // $name.next().hide();
                    // err_name = false;
                    var url = "/manager/exists/?name=" + $name.val();
                    $.get(url, function (data) {
                        var count = data['count'];
                        if (count == 1) {
                            err_name1 = false;
                        }
                        else {
                            $name.next().html("用户名不存在").show();
                            err_name1 = true;
                        }
                    })

                }
                else {
                    $name.next().html('请输入包含数字,字母或下划线的5到11位用户名').show();
                    err_name1 = true;
                }

            }

            var re_pwd = /^\w{8,20}$/i;

            function check_pwd() {
                if (re_pwd.test($pwd.val())) {
                    $pwd.next().hide();
                    err_pwd1 = false;
                }
                else {
                    $pwd.next().html('请输入包含数字,字母或下划线的8到20位密码').show();
                    err_pwd1 = true;
                }
            }

            $('#login').bind('click', function () {
                if (err_name1 == true || err_pwd1 == true) {
                    return false;
                }

            })
            $(document).keyup(function (event) {
                if (event.keyCode == 13) {
                    $("#login").trigger("click");
                }
            });


        })
    </script>
{% endblock js %}

templates/bookmanage/manager_add_card_handle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url "bookmanage:manager_add_card" %}">
    {% csrf_token %}
    name:<input type="text" name="name"/><br/>
    department:<input type="text" name="department"/><br/>
    <input type="radio" name="type" value="student" checked="checked"/>student
    <input type="radio" name="type" value="teacher"/>teacher
    <input type="submit" value="submit"/>
</form>
</body>
</html>