bookmanage/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.index,name='index'),

    path('base/',views.base,name="base"),

    path('book/add/',views.book_add,name="book_add"),
    path('books/add/',views.books_add,name="books_add"),

    path('query/',views.query,name='query'),
    path('query/books/',views.query_books,name='query_books'),
    path('card/',views.card,name='card'),
    path('card/login/',views.card_login,name='card_login'),
    path('card/login/notexists/',views.card_login_notexists,name='card_login_notexists'),
    path('card/handle/',views.card_handle,name='card_handle'),
    path('card/login/handle/',views.card_login_handle,name='card_login_handle'),
    path('card/exit/',views.card_exit,name='card_exit'),
    path('card/exists/',views.card_exists,name='card_exists'),
    path('card/books/',views.card_books,name='card_books'),
    path('cards/query/',views.cards_query,name='cards_query'),
    path('card/delete/',views.card_delete,name='card_delete'),
    path('card/borrowed/',views.card_borrowed,name='card_borrowed'),

    path('booktitle/query/',views.booktitle_query,name='booktitle_query'),
    path('books/query/',views.books_query,name="books_query"),
    path('bookid_cardid/exists/',views.bookid_cardid_exists,name='bookid_cardid_exists'),


    path('manager/',views.manager,name='manager'),
    path('manager/login/',views.manager_login,name='manager_login'),
    path('manager/login/notexists',views.manager_login_notexists,name='manager_login_notexists'),
    path('manager/login/handle/',views.manager_login_handle,name='manager_login_handle'),
    path('manager/exit/',views.manager_exit,name='manager_exit'),
    path('manager/create/',views.manager_create,name='manager_create'),
    path('manager/create/handle/',views.manager_create_handle,name='manager_create_handle'),
    path('manager/add/books/',views.manager_add_books,name='manager_add_books'),
    path('manager/add/card/',views.manager_add_card,name='manager_add_card'),
    path('manager/add/card/handle/',views.manager_add_card_handle,name='manager_add_card_handle'),
    path('manager/exists/', views.manager_exists, name='manager_exists'),

]

books/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('bookmanage.urls','bookmanage'),namespace='bookmanage')),
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>{{ title }} 图书管理系统</title>
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/lib/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/lib/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/static/lib/pagination/pagination.css">
    <link rel="stylesheet" href="/static/css/main.css">
    {% block css %}{% endblock %}
    <!--[if lt IE 9]>
        <script type="text/javascript" src="/static/lib/respond/respond.min.js"></script>
        <script type="text/javascript" src="/static/lib/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
</head>
<body>
{#    home#}
    <header id="home">
            <div class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                <a href="{% url 'bookmanage:index' %}" class="navbar-brand">图书管理系统</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navMenu "><i class="navbar-toggler-icon"></i></button>
                <div class="collapse navbar-collapse" id="navMenu">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a href="{% url "bookmanage:query" %}" class="nav-link"><i class="fas fa-search"></i>&nbsp;查询</a></li>
                        <li class="nav-item"><a href="{% url "bookmanage:card" %}" class="nav-link"><i class="fas fa-arrow-alt-circle-down"></i>&nbsp;借书</a></li>
                        <li class="nav-item"><a href="{% url "bookmanage:card" %}" class="nav-link"><i class="fas fa-redo"></i>&nbsp;还书</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>
{#    home#}

{% block body %}{% endblock body%}
{#footer#}
    <footer id="copyright">
        <div class="container text-center">
            <p>CopyRight © 2018 XXX技术有限公司 All Rights Reserved</p>
        </div>
    </footer>

    <script type="text/javascript" src="/static/lib/jquery/jquery-3.3.1.min.js"></script>
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>#}
    <script type="text/javascript" src="/static/lib/popper/popper.min.js"></script>
    <!-- the above sentence is required for the tooltip -->
    <script type="text/javascript" src="/static/lib/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/lib/pagination/pagination.js"></script>
    <script type="text/javascript" src="/static/lib/twbspagination/jquery.twbsPagination.js"></script>
    <script type="text/javascript" src="/static/js/main.js"></script>
    {% block js %}{% endblock %}
</body>
</html>